from __future__ import annotations

from pathlib import Path


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# This package lives in:
#
#   ...\Documents\Paradox Interactive\Victoria II\save games\tracker\core\config.py
#
# Therefore:
#
#   REPO_DIR = ...\save games\tracker
#   SAVE_DIR = ...\save games
#
# Note: the save directory is under your Documents folder, not under the
# game install (GAME_DIR below points at the install, used only to locate
# game data such as inventions/*.txt).
#
# The output directory (the CSV history and processed-dates ledger) is chosen
# by the user at runtime and must match the save game being tracked.
#
REPO_DIR = Path(__file__).resolve().parent.parent
SAVE_DIR = REPO_DIR.parent

# User setting: edit this to point at your Victoria II installation.
# Used by setup.initialise to locate game data (e.g. inventions/*.txt);
# --game-dir on the command line overrides it.
GAME_DIR = Path(r"C:\Program Files (x86)\Steam\steamapps\common\Victoria 2")

# Reference data generated by setup.initialise, one directory per game
# variant: data/vanilla/ is the committed vanilla default, and modded
# installs generate sibling directories (data/<mod>/).
DATA_DIR = REPO_DIR / "data"
VANILLA_DATA_DIR = DATA_DIR / "vanilla"

OUTPUT_FILENAME = "goods_prices.csv"
PROCESSED_FILENAME = "processed_dates.json"

# Watch mode tracks only the live autosave. The rotated files are
# deliberately ignored: after a new save game's first autosave, the game
# cascades the previous session's saves into oldautosave.v2 /
# olderautosave.v2, and recording those would pollute the current watch
# with a different save game's data. Consequence: an autosave missed while
# the watcher is down is not backfilled from the rotated files.
WATCH_FILES = [
    "autosave.v2",
]
